### ISSUE TITLE
Skysafari server crashing after a long night

### ISSUE THREAD

**Issue by mrosseel** [brickbots/PiFinder#241]
Sep 27 20:53:17 pifinder-mr2 python[810]: 2024-09-27 20:53:17,622 SkySafariServer-PosServer:WARNING:Unknown Command: :RG#
Sep 27 20:53:22 pifinder-mr2 python[810]: 2024-09-27 20:53:22,300 SkySafariServer-PosServer:WARNING:Unknown Command: :RG#
Sep 27 20:58:06 pifinder-mr2 python[810]: 2024-09-27 20:58:06,169 SkySafariServer-PosServer:WARNING:Unknown Command: :Me#
Sep 27 20:58:07 pifinder-mr2 python[810]: 2024-09-27 20:58:07,138 SkySafariServer-PosServer:WARNING:Unknown Command: :Qe#
Sep 27 20:58:08 pifinder-mr2 python[810]: 2024-09-27 20:58:08,781 SkySafariServer-PosServer:WARNING:Unknown Command: :Me#
Sep 27 20:58:08 pifinder-mr2 python[810]: 2024-09-27 20:58:08,850 SkySafariServer-PosServer:WARNING:Unknown Command: :Qe#
Sep 27 20:58:09 pifinder-mr2 python[810]: 2024-09-27 20:58:09,729 SkySafariServer-PosServer:WARNING:Unknown Command: :Me#
Sep 27 20:58:09 pifinder-mr2 python[810]: 2024-09-27 20:58:09,763 SkySafariServer-PosServer:WARNING:Unknown Command: :Qe#
Sep 27 21:02:05 pifinder-mr2 python[810]: 2024-09-27 21:02:05,844 SkySafariServer-PosServer:ERROR:[Errno 104] Connection reset by peer
Sep 27 21:02:05 pifinder-mr2 python[810]: Traceback (most recent call last):
Sep 27 21:02:05 pifinder-mr2 python[810]:   File "/home/pifinder/PiFinder/python/PiFinder/pos_server.py", line 196, in run_server
Sep 27 21:02:05 pifinder-mr2 python[810]:     in_data = client_socket.recv(1024).decode()
Sep 27 21:02:05 pifinder-mr2 python[810]: ConnectionResetError: [Errno 104] Connection reset by peer
Sep 27 21:02:05 pifinder-mr2 python[810]: 2024-09-27 21:02:05,849 SkySafariServer-PosServer:ERROR:An error occurred in the skysafari server, exiting!Sep 27 21:02:05 pifinder-mr2 python[810]: Traceback (most recent call last):
Sep 27 21:02:05 pifinder-mr2 python[810]:   File "/home/pifinder/PiFinder/python/PiFinder/pos_server.py", line 196, in run_server
Sep 27 21:02:05 pifinder-mr2 python[810]:     in_data = client_socket.recv(1024).decode()
Sep 27 21:02:05 pifinder-mr2 python[810]: ConnectionResetError: [Errno 104] Connection reset by peer
Sep 27 21:02:05 pifinder-mr2 python[810]: 2024-09-27 21:02:05,849 SkySafariServer-PosServer:ERROR:An error occurred in the skysafari server, exiting!

**Comment by mrosseel** [comment]
should be solved by the merged PR
